/*
 * AUTOGENERATED - DON'T EDIT
 * Your edits in this file will be overwritten in the next build!
 * Modify the docusaurus.config.js file at your site's root instead.
 */
export default {
  "title": "Linga Raj M — Technical Writer",
  "tagline": "7+ Years of Driving User Documentation Excellence",
  "url": "https://lingaraj-tw.github.io",
  "baseUrl": "/Technical-Writing-Portfolio/",
  "onBrokenLinks": "throw",
  "favicon": "img/favicon.ico",
  "organizationName": "Lingaraj-TW",
  "projectName": "Technical-Writing-Portfolio",
  "presets": [
    [
      "@docusaurus/preset-classic",
      {
        "docs": {
          "sidebarPath": "/Users/lingarajm/Documents/GitHub/Technical-Writing-Portfolio/sidebars.js",
          "editUrl": "https://github.com/Lingaraj-TW/Technical-Writing-Portfolio/edit/site-docusaurus/"
        },
        "blog": false,
        "theme": {
          "customCss": "/Users/lingarajm/Documents/GitHub/Technical-Writing-Portfolio/src/css/custom.css"
        }
      }
    ]
  ],
  "themeConfig": {
    "navbar": {
      "title": "Linga Raj M",
      "logo": {
        "alt": "Linga Raj M",
        "src": "img/logo.svg"
      },
      "items": [
        {
          "to": "/docs/intro",
          "label": "Portfolio",
          "position": "left"
        },
        {
          "to": "/about",
          "label": "About",
          "position": "left"
        },
        {
          "to": "/docs/case-study-template",
          "label": "Case study template",
          "position": "left"
        },
        {
          "href": "https://www.linkedin.com/in/lingarajm/",
          "label": "LinkedIn",
          "position": "right"
        },
        {
          "href": "mailto:lingaraj501@gmail.com",
          "label": "Say hello",
          "position": "right"
        },
        {
          "href": "/assets/cv/Linga_Raj_M_Technical_Writer_Resume.pdf",
          "label": "CV",
          "position": "right"
        }
      ],
      "hideOnScroll": false
    },
    "footer": {
      "style": "dark",
      "links": [
        {
          "title": "Work",
          "items": [
            {
              "label": "Portfolio",
              "to": "/docs/intro"
            },
            {
              "label": "Things I've worked on",
              "to": "/projects"
            }
          ]
        },
        {
          "title": "Connect",
          "items": [
            {
              "label": "LinkedIn",
              "href": "https://www.linkedin.com/in/lingarajm/"
            },
            {
              "label": "Email",
              "href": "mailto:lingaraj501@gmail.com"
            }
          ]
        }
      ],
      "copyright": "© 2026 Linga Raj M."
    },
    "prism": {
      "theme": {
        "plain": {
          "color": "#393A34",
          "backgroundColor": "#f6f8fa"
        },
        "styles": [
          {
            "types": [
              "comment",
              "prolog",
              "doctype",
              "cdata"
            ],
            "style": {
              "color": "#999988",
              "fontStyle": "italic"
            }
          },
          {
            "types": [
              "namespace"
            ],
            "style": {
              "opacity": 0.7
            }
          },
          {
            "types": [
              "string",
              "attr-value"
            ],
            "style": {
              "color": "#e3116c"
            }
          },
          {
            "types": [
              "punctuation",
              "operator"
            ],
            "style": {
              "color": "#393A34"
            }
          },
          {
            "types": [
              "entity",
              "url",
              "symbol",
              "number",
              "boolean",
              "variable",
              "constant",
              "property",
              "regex",
              "inserted"
            ],
            "style": {
              "color": "#36acaa"
            }
          },
          {
            "types": [
              "atrule",
              "keyword",
              "attr-name",
              "selector"
            ],
            "style": {
              "color": "#00a4db"
            }
          },
          {
            "types": [
              "function",
              "deleted",
              "tag"
            ],
            "style": {
              "color": "#d73a49"
            }
          },
          {
            "types": [
              "function-variable"
            ],
            "style": {
              "color": "#6f42c1"
            }
          },
          {
            "types": [
              "tag",
              "selector",
              "keyword"
            ],
            "style": {
              "color": "#00009f"
            }
          }
        ]
      },
      "additionalLanguages": [
        "bash",
        "powershell"
      ],
      "magicComments": [
        {
          "className": "theme-code-block-highlighted-line",
          "line": "highlight-next-line",
          "block": {
            "start": "highlight-start",
            "end": "highlight-end"
          }
        }
      ]
    },
    "colorMode": {
      "defaultMode": "light",
      "disableSwitch": false,
      "respectPrefersColorScheme": false
    },
    "docs": {
      "versionPersistence": "localStorage",
      "sidebar": {
        "hideable": false,
        "autoCollapseCategories": false
      }
    },
    "blog": {
      "sidebar": {
        "groupByYear": true
      }
    },
    "metadata": [],
    "tableOfContents": {
      "minHeadingLevel": 2,
      "maxHeadingLevel": 3
    }
  },
  "baseUrlIssueBanner": true,
  "i18n": {
    "defaultLocale": "en",
    "path": "i18n",
    "locales": [
      "en"
    ],
    "localeConfigs": {}
  },
  "future": {
    "v4": {
      "removeLegacyPostBuildHeadAttribute": false,
      "useCssCascadeLayers": false
    },
    "experimental_faster": {
      "swcJsLoader": false,
      "swcJsMinimizer": false,
      "swcHtmlMinimizer": false,
      "lightningCssMinimizer": false,
      "mdxCrossCompilerCache": false,
      "rspackBundler": false,
      "rspackPersistentCache": false,
      "ssgWorkerThreads": false
    },
    "experimental_storage": {
      "type": "localStorage",
      "namespace": false
    },
    "experimental_router": "browser"
  },
  "onBrokenAnchors": "warn",
  "onDuplicateRoutes": "warn",
  "staticDirectories": [
    "static"
  ],
  "customFields": {},
  "plugins": [],
  "themes": [],
  "scripts": [],
  "headTags": [],
  "stylesheets": [],
  "clientModules": [],
  "titleDelimiter": "|",
  "noIndex": false,
  "markdown": {
    "format": "mdx",
    "mermaid": false,
    "emoji": true,
    "mdx1Compat": {
      "comments": true,
      "admonitions": true,
      "headingIds": true
    },
    "anchors": {
      "maintainCase": false
    },
    "hooks": {
      "onBrokenMarkdownLinks": "warn",
      "onBrokenMarkdownImages": "throw"
    }
  }
};
